<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bool $fp
 * @property bool $upl
 * @property bool $service
 * @property string $kdnr
 * @property string $titel
 * @property string $name
 * @property string $vorname
 * @property date $gebdat
 * @property string $strasse
 * @property string $hnr
 * @property string $plz
 * @property string $ort
 * @property integer $kto
 * @property integer $blz
 * @property varchar $vorwahl
 * @property varchar $rfn
 * @property varchar $fax
 * @property varchar $mail
 * @property bool $bestellt
 * @property date $termin
 * @property varchar $feld1
 * @property varchar $feld2
 * @property varchar $feld3
 * @property integer $tarif_id
 * @property integer $laufzeit_id
 * @property integer $guthaben_id
 * @property integer $modem_id
 * @property integer $portierung_id
 * @property integer $ip_id
 * @property integer $user_id
 * @property Tarif $Tarif
 * @property Laufzeit $Laufzeit
 * @property Guthaben $Guthaben
 * @property Modem $Modem
 * @property Portierung $Portierung
 * @property Ip $Ip
 * @property sfGuardUser $sfGuardUser
 * 
 * @method bool        getFp()            Returns the current record's "fp" value
 * @method bool        getUpl()           Returns the current record's "upl" value
 * @method bool        getService()       Returns the current record's "service" value
 * @method string      getKdnr()          Returns the current record's "kdnr" value
 * @method string      getTitel()         Returns the current record's "titel" value
 * @method string      getName()          Returns the current record's "name" value
 * @method string      getVorname()       Returns the current record's "vorname" value
 * @method date        getGebdat()        Returns the current record's "gebdat" value
 * @method string      getStrasse()       Returns the current record's "strasse" value
 * @method string      getHnr()           Returns the current record's "hnr" value
 * @method string      getPlz()           Returns the current record's "plz" value
 * @method string      getOrt()           Returns the current record's "ort" value
 * @method integer     getKto()           Returns the current record's "kto" value
 * @method integer     getBlz()           Returns the current record's "blz" value
 * @method varchar     getVorwahl()       Returns the current record's "vorwahl" value
 * @method varchar     getRfn()           Returns the current record's "rfn" value
 * @method varchar     getFax()           Returns the current record's "fax" value
 * @method varchar     getMail()          Returns the current record's "mail" value
 * @method bool        getBestellt()      Returns the current record's "bestellt" value
 * @method date        getTermin()        Returns the current record's "termin" value
 * @method varchar     getFeld1()         Returns the current record's "feld1" value
 * @method varchar     getFeld2()         Returns the current record's "feld2" value
 * @method varchar     getFeld3()         Returns the current record's "feld3" value
 * @method integer     getTarifId()       Returns the current record's "tarif_id" value
 * @method integer     getLaufzeitId()    Returns the current record's "laufzeit_id" value
 * @method integer     getGuthabenId()    Returns the current record's "guthaben_id" value
 * @method integer     getModemId()       Returns the current record's "modem_id" value
 * @method integer     getPortierungId()  Returns the current record's "portierung_id" value
 * @method integer     getIpId()          Returns the current record's "ip_id" value
 * @method integer     getUserId()        Returns the current record's "user_id" value
 * @method Tarif       getTarif()         Returns the current record's "Tarif" value
 * @method Laufzeit    getLaufzeit()      Returns the current record's "Laufzeit" value
 * @method Guthaben    getGuthaben()      Returns the current record's "Guthaben" value
 * @method Modem       getModem()         Returns the current record's "Modem" value
 * @method Portierung  getPortierung()    Returns the current record's "Portierung" value
 * @method Ip          getIp()            Returns the current record's "Ip" value
 * @method sfGuardUser getSfGuardUser()   Returns the current record's "sfGuardUser" value
 * @method Article     setFp()            Sets the current record's "fp" value
 * @method Article     setUpl()           Sets the current record's "upl" value
 * @method Article     setService()       Sets the current record's "service" value
 * @method Article     setKdnr()          Sets the current record's "kdnr" value
 * @method Article     setTitel()         Sets the current record's "titel" value
 * @method Article     setName()          Sets the current record's "name" value
 * @method Article     setVorname()       Sets the current record's "vorname" value
 * @method Article     setGebdat()        Sets the current record's "gebdat" value
 * @method Article     setStrasse()       Sets the current record's "strasse" value
 * @method Article     setHnr()           Sets the current record's "hnr" value
 * @method Article     setPlz()           Sets the current record's "plz" value
 * @method Article     setOrt()           Sets the current record's "ort" value
 * @method Article     setKto()           Sets the current record's "kto" value
 * @method Article     setBlz()           Sets the current record's "blz" value
 * @method Article     setVorwahl()       Sets the current record's "vorwahl" value
 * @method Article     setRfn()           Sets the current record's "rfn" value
 * @method Article     setFax()           Sets the current record's "fax" value
 * @method Article     setMail()          Sets the current record's "mail" value
 * @method Article     setBestellt()      Sets the current record's "bestellt" value
 * @method Article     setTermin()        Sets the current record's "termin" value
 * @method Article     setFeld1()         Sets the current record's "feld1" value
 * @method Article     setFeld2()         Sets the current record's "feld2" value
 * @method Article     setFeld3()         Sets the current record's "feld3" value
 * @method Article     setTarifId()       Sets the current record's "tarif_id" value
 * @method Article     setLaufzeitId()    Sets the current record's "laufzeit_id" value
 * @method Article     setGuthabenId()    Sets the current record's "guthaben_id" value
 * @method Article     setModemId()       Sets the current record's "modem_id" value
 * @method Article     setPortierungId()  Sets the current record's "portierung_id" value
 * @method Article     setIpId()          Sets the current record's "ip_id" value
 * @method Article     setUserId()        Sets the current record's "user_id" value
 * @method Article     setTarif()         Sets the current record's "Tarif" value
 * @method Article     setLaufzeit()      Sets the current record's "Laufzeit" value
 * @method Article     setGuthaben()      Sets the current record's "Guthaben" value
 * @method Article     setModem()         Sets the current record's "Modem" value
 * @method Article     setPortierung()    Sets the current record's "Portierung" value
 * @method Article     setIp()            Sets the current record's "Ip" value
 * @method Article     setSfGuardUser()   Sets the current record's "sfGuardUser" value
 * 
 * @package    shopping_cart
 * @subpackage model
 * @author     Stefan Riedel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('fp', 'bool', null, array(
             'type' => 'bool',
             ));
        $this->hasColumn('upl', 'bool', null, array(
             'type' => 'bool',
             ));
        $this->hasColumn('service', 'bool', null, array(
             'type' => 'bool',
             ));
        $this->hasColumn('kdnr', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('titel', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('vorname', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('gebdat', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('strasse', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('hnr', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('plz', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('ort', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('kto', 'integer', 10, array(
             'type' => 'integer',
             'zerofill' => true,
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('blz', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 8,
             ));
        $this->hasColumn('vorwahl', 'varchar', 6, array(
             'type' => 'varchar',
             'length' => 6,
             ));
        $this->hasColumn('rfn', 'varchar', 10, array(
             'type' => 'varchar',
             'length' => 10,
             ));
        $this->hasColumn('fax', 'varchar', 15, array(
             'type' => 'varchar',
             'length' => 15,
             ));
        $this->hasColumn('mail', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('bestellt', 'bool', null, array(
             'type' => 'bool',
             ));
        $this->hasColumn('termin', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('feld1', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('feld2', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('feld3', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('tarif_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('laufzeit_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('guthaben_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('modem_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('portierung_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('ip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tarif', array(
             'local' => 'tarif_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Laufzeit', array(
             'local' => 'laufzeit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Guthaben', array(
             'local' => 'guthaben_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Modem', array(
             'local' => 'modem_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Portierung', array(
             'local' => 'portierung_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Ip', array(
             'local' => 'ip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
        $this->actAs($softdelete0);
    }
}