<?php

/**
 * BaseZahlintervall
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $beschreibung
 * @property Doctrine_Collection $Tarif
 * @property Doctrine_Collection $Laufzeit
 * @property Doctrine_Collection $Guthaben
 * @property Doctrine_Collection $Modem
 * @property Doctrine_Collection $Portierung
 * @property Doctrine_Collection $Ip
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getBeschreibung() Returns the current record's "beschreibung" value
 * @method Doctrine_Collection getTarif()        Returns the current record's "Tarif" collection
 * @method Doctrine_Collection getLaufzeit()     Returns the current record's "Laufzeit" collection
 * @method Doctrine_Collection getGuthaben()     Returns the current record's "Guthaben" collection
 * @method Doctrine_Collection getModem()        Returns the current record's "Modem" collection
 * @method Doctrine_Collection getPortierung()   Returns the current record's "Portierung" collection
 * @method Doctrine_Collection getIp()           Returns the current record's "Ip" collection
 * @method Zahlintervall       setName()         Sets the current record's "name" value
 * @method Zahlintervall       setBeschreibung() Sets the current record's "beschreibung" value
 * @method Zahlintervall       setTarif()        Sets the current record's "Tarif" collection
 * @method Zahlintervall       setLaufzeit()     Sets the current record's "Laufzeit" collection
 * @method Zahlintervall       setGuthaben()     Sets the current record's "Guthaben" collection
 * @method Zahlintervall       setModem()        Sets the current record's "Modem" collection
 * @method Zahlintervall       setPortierung()   Sets the current record's "Portierung" collection
 * @method Zahlintervall       setIp()           Sets the current record's "Ip" collection
 * 
 * @package    shopping_cart
 * @subpackage model
 * @author     Stefan Riedel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZahlintervall extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zahlintervall');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('beschreibung', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tarif', array(
             'local' => 'id',
             'foreign' => 'zahlintervall_id'));

        $this->hasMany('Laufzeit', array(
             'local' => 'id',
             'foreign' => 'zahlintervall_id'));

        $this->hasMany('Guthaben', array(
             'local' => 'id',
             'foreign' => 'zahlintervall_id'));

        $this->hasMany('Modem', array(
             'local' => 'id',
             'foreign' => 'zahlintervall_id'));

        $this->hasMany('Portierung', array(
             'local' => 'id',
             'foreign' => 'zahlintervall_id'));

        $this->hasMany('Ip', array(
             'local' => 'id',
             'foreign' => 'zahlintervall_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}