<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    shopping_cart
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Article.class.php 3 2011-07-18 12:45:10Z sriedel $
 */
class Article extends BaseArticle
{
    public function save(Doctrine_Connection $conn = null) {
        $this->user_id = sfContext::getInstance()->getUser()->getId();
        parent::save($conn);
    }
}
