<?php

/**
 * IpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ip');
    }
    public function findWithZahlintervall($id)
    {
        $q = Doctrine_Query::create()
                ->from($this->getTableName() . ' x')
                ->leftJoin('x.Zahlintervall z')
                ->where('x.id = ?', $id);
        return $q->fetchOne();
    }
}