<?php

/**
 * Modem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    shopping_cart
 * @subpackage model
 * @author     Stefan Riedel
 * @version    SVN: $Id: Modem.class.php 3 2011-07-18 12:45:10Z sriedel $
 */
class Modem extends BaseModem
{
    public function __toString() {
        return $this->beschreibung;
    }
}
