<?php

/**
 * Portierung
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    shopping_cart
 * @subpackage model
 * @author     Stefan Riedel
 * @version    SVN: $Id: Portierung.class.php 3 2011-07-18 12:45:10Z sriedel $
 */
class Portierung extends BasePortierung {

    public function __toString() {
        return (!empty($this->beschreibung)) ? $this->beschreibung : '';
    }

}
