<?php

/**
 * Zahlintervall
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    shopping_cart
 * @subpackage model
 * @author     Stefan Riedel
 * @version    SVN: $Id: Zahlintervall.class.php 3 2011-07-18 12:45:10Z sriedel $
 */
class Zahlintervall extends BaseZahlintervall
{
}
